// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "InfiltratorProfile.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Infiltrator {

namespace {

const ::google::protobuf::Descriptor* Profile_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Profile_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_InfiltratorProfile_2eproto() {
  protobuf_AddDesc_InfiltratorProfile_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "InfiltratorProfile.proto");
  GOOGLE_CHECK(file != NULL);
  Profile_descriptor_ = file->message_type(0);
  static const int Profile_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Profile, allgold_),
  };
  Profile_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Profile_descriptor_,
      Profile::default_instance_,
      Profile_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Profile, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Profile, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Profile));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_InfiltratorProfile_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Profile_descriptor_, &Profile::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_InfiltratorProfile_2eproto() {
  delete Profile::default_instance_;
  delete Profile_reflection_;
}

void protobuf_AddDesc_InfiltratorProfile_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\030InfiltratorProfile.proto\022\013Infiltrator\""
    "\032\n\007Profile\022\017\n\007allGold\030\002 \002(\r", 67);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "InfiltratorProfile.proto", &protobuf_RegisterTypes);
  Profile::default_instance_ = new Profile();
  Profile::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_InfiltratorProfile_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_InfiltratorProfile_2eproto {
  StaticDescriptorInitializer_InfiltratorProfile_2eproto() {
    protobuf_AddDesc_InfiltratorProfile_2eproto();
  }
} static_descriptor_initializer_InfiltratorProfile_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int Profile::kAllGoldFieldNumber;
#endif  // !_MSC_VER

Profile::Profile()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Profile::InitAsDefaultInstance() {
}

Profile::Profile(const Profile& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Profile::SharedCtor() {
  _cached_size_ = 0;
  allgold_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Profile::~Profile() {
  SharedDtor();
}

void Profile::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Profile::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Profile::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Profile_descriptor_;
}

const Profile& Profile::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_InfiltratorProfile_2eproto();  return *default_instance_;
}

Profile* Profile::default_instance_ = NULL;

Profile* Profile::New() const {
  return new Profile;
}

void Profile::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    allgold_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Profile::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 allGold = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &allgold_)));
          set_has_allgold();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Profile::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 allGold = 2;
  if (has_allgold()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->allgold(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Profile::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 allGold = 2;
  if (has_allgold()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->allgold(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Profile::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 allGold = 2;
    if (has_allgold()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->allgold());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Profile::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Profile* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Profile*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Profile::MergeFrom(const Profile& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_allgold()) {
      set_allgold(from.allgold());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Profile::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Profile::CopyFrom(const Profile& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Profile::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void Profile::Swap(Profile* other) {
  if (other != this) {
    std::swap(allgold_, other->allgold_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Profile::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Profile_descriptor_;
  metadata.reflection = Profile_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Infiltrator

// @@protoc_insertion_point(global_scope)
